import { createHash, randomBytes, randomUUID } from 'node:crypto';

const AGENT_ACTIONS = new Set(['obs_bridge_agent_poll','obs_bridge_agent_complete']);
const USER_COMMANDS = new Set([
  'set_scene','refresh_state','start_recording','stop_recording','pause_recording','resume_recording',
  'show_lower_third','clear_overlay','create_scene','create_source','remove_source','set_source_visibility',
  'set_source_transform','move_source_up','move_source_down'
]);
const OVERLAY_POSITIONS = new Set(['bottom_left','bottom_center','bottom_right','top_left','top_center','top_right']);
const AGENT_HEARTBEAT_WRITE_MS=15000, BRIDGE_ONLINE_WINDOW_MS=30000, AGENT_AUTH_CACHE_TTL_MS=30000, AGENT_COMMAND_POLL_MS=5000;
const agentBridgeCache=new Map(), agentRuntime=new Map();
const clean=(v,f='')=>String(v??'').trim()||f;
const cleanNullable=v=>clean(v)||null;
function makeError(message,code,status=400){const e=new Error(message);e.code=code;e.status=status;return e;}
const tokenHash=t=>createHash('sha256').update(String(t||''),'utf8').digest('hex');
const json=v=>JSON.stringify(v??{});
function normalizeScenes(v){return Array.isArray(v)?v.map(s=>clean(typeof s==='string'?s:s?.sceneName||s?.name)).filter(Boolean).slice(0,100):[];}
function bridgeIsOnline(r){if(!r?.last_seen_at)return false;const t=new Date(r.last_seen_at).getTime();return Number.isFinite(t)&&Date.now()-t<BRIDGE_ONLINE_WINDOW_MS;}
function publicBridge(r){if(!r)return null;const online=bridgeIsOnline(r),connected=Boolean(online&&r.obs_connected&&!r.revoked_at);return{id:r.id,name:r.name,token_hint:r.token_hint||null,status:r.revoked_at?'revoked':connected?'connected':online?'bridge_online':r.status==='pairing'?'pairing':'offline',online,connected,obs_endpoint:r.obs_endpoint||null,obs_studio_version:r.obs_studio_version||null,obs_websocket_version:r.obs_websocket_version||null,current_scene:r.current_scene||null,scenes:Array.isArray(r.scenes)?r.scenes:[],capabilities:r.capabilities&&typeof r.capabilities==='object'?r.capabilities:{},last_seen_at:r.last_seen_at||null,last_error:r.last_error||null,created_at:r.created_at||null,updated_at:r.updated_at||null};}
async function findOwnedBridge(sql,ownerUserId,requestedBridgeId=null){const ownerId=String(ownerUserId||'').trim(),bridgeId=clean(requestedBridgeId);let rows;if(bridgeId)rows=await sql`SELECT * FROM creapd.obs_bridges WHERE id=${bridgeId} AND owner_user_id=${ownerId} AND revoked_at IS NULL LIMIT 1`;else rows=await sql`SELECT * FROM creapd.obs_bridges WHERE owner_user_id=${ownerId} AND revoked_at IS NULL ORDER BY updated_at DESC LIMIT 1`;return rows?.[0]||null;}
async function requireAgentBridge(sql,bridgeToken){const token=clean(bridgeToken);if(!token)throw makeError('Bridge token is required','OBS_BRIDGE_TOKEN_REQUIRED',401);const hash=tokenHash(token),cached=agentBridgeCache.get(hash);if(cached&&Date.now()-cached.verifiedAt<AGENT_AUTH_CACHE_TTL_MS)return cached.bridge;const [bridge]=await sql`SELECT * FROM creapd.obs_bridges WHERE token_hash=${hash} AND revoked_at IS NULL LIMIT 1`;if(!bridge)throw makeError('Bridge token is invalid or revoked','OBS_BRIDGE_TOKEN_INVALID',401);agentBridgeCache.set(hash,{bridge,verifiedAt:Date.now()});return bridge;}
function resetAgentCaches(){agentBridgeCache.clear();agentRuntime.clear();}
async function createOrRotateBridge(sql,ownerUserId,name){const ownerId=String(ownerUserId),token=`creapd_obs_${randomBytes(32).toString('base64url')}`,hash=tokenHash(token),hint=token.slice(-6),existing=await findOwnedBridge(sql,ownerId);let bridge;if(existing)[bridge]=await sql`UPDATE creapd.obs_bridges SET token_hash=${hash},token_hint=${hint},name=${clean(name,existing.name||'Studio OBS')},status='pairing',obs_connected=false,last_error=NULL,updated_at=now() WHERE id=${existing.id} AND owner_user_id=${ownerId} RETURNING *`;else [bridge]=await sql`INSERT INTO creapd.obs_bridges(id,owner_user_id,name,token_hash,token_hint,status) VALUES(${randomUUID()},${ownerId},${clean(name,'Studio OBS')},${hash},${hint},'pairing') RETURNING *`;resetAgentCaches();return{bridge:publicBridge(bridge),bridge_token:token,token_shown_once:true};}
async function saveTalkSegmentScene(sql,ownerUserId,body){const ownerId=String(ownerUserId||'').trim(),segmentId=clean(body.segment_id);if(!segmentId)throw makeError('segment_id is required','OBS_SEGMENT_ID_REQUIRED');const [existing]=await sql`SELECT id,configuration_id FROM creapd.talk_segments WHERE id=${segmentId} AND owner_user_id=${ownerId} LIMIT 1`;if(!existing)throw makeError('Talk segment not found','TALK_SEGMENT_NOT_FOUND',404);const requested=clean(body.configuration_id);if(requested&&requested!==existing.configuration_id)throw makeError('Talk segment does not belong to this production','OBS_SEGMENT_CONFIGURATION_MISMATCH',409);const sceneName=cleanNullable(body.scene_name);if(sceneName&&sceneName.length>160)throw makeError('OBS scene name is too long','OBS_SCENE_NAME_TOO_LONG');const [segment]=await sql`UPDATE creapd.talk_segments SET obs_scene=${sceneName},updated_at=now() WHERE id=${segmentId} AND owner_user_id=${ownerId} RETURNING *`;return{segment:{...segment,order:segment.order_index,created_date:segment.created_at||null,updated_date:segment.updated_at||null},mapping_saved:true};}
async function enqueueCommand(sql,ownerUserId,body){const ownerId=String(ownerUserId),bridge=await findOwnedBridge(sql,ownerId,body.bridge_id);if(!bridge)throw makeError('OBS bridge not found','OBS_BRIDGE_NOT_FOUND',404);const commandType=clean(body.command_type);if(!USER_COMMANDS.has(commandType))throw makeError('Unsupported OBS command','OBS_COMMAND_UNSUPPORTED');let payload=body.payload&&typeof body.payload==='object'&&!Array.isArray(body.payload)?{...body.payload}:{};if(commandType==='set_scene'&&!clean(payload.scene_name))throw makeError('scene_name is required','OBS_SCENE_NAME_REQUIRED');if(commandType==='create_scene'&&!clean(payload.scene_name))throw makeError('scene_name is required','OBS_SCENE_NAME_REQUIRED');if(['remove_source','set_source_visibility','set_source_transform','move_source_up','move_source_down'].includes(commandType)&&!clean(payload.source_name))throw makeError('source_name is required','OBS_SOURCE_NAME_REQUIRED');if(commandType==='create_source'){if(!clean(payload.scene_name))throw makeError('scene_name is required','OBS_SCENE_NAME_REQUIRED');if(!clean(payload.source_name))throw makeError('source_name is required','OBS_SOURCE_NAME_REQUIRED');if(!clean(payload.source_type))throw makeError('source_type is required','OBS_SOURCE_TYPE_REQUIRED');}
if(commandType==='show_lower_third'){const title=clean(payload.title);if(!title)throw makeError('Lower-third title is required','OBS_LOWER_THIRD_TITLE_REQUIRED');const p=clean(payload.position,'bottom_left').toLowerCase();payload={title:title.slice(0,120),subtitle:clean(payload.subtitle).slice(0,180),label:clean(payload.label,'CREAPD LIVE').slice(0,40),position:OVERLAY_POSITIONS.has(p)?p:'bottom_left'};}
const [command]=await sql`INSERT INTO creapd.obs_commands(id,bridge_id,owner_user_id,session_type,session_id,command_type,payload,status) VALUES(${randomUUID()},${bridge.id},${ownerId},${cleanNullable(body.session_type)},${cleanNullable(body.session_id)},${commandType},${json(payload)}::jsonb,'pending') RETURNING id,bridge_id,command_type,payload,status,requested_at`;const runtime=agentRuntime.get(bridge.id)||{};agentRuntime.set(bridge.id,{...runtime,lastCommandPollAt:0});return{command:{...command,payload:command.payload||{}}};}
export function isObsBridgeAgentAction(action){return AGENT_ACTIONS.has(clean(action));}
export async function runObsBridgeUserAction({sql,ownerUserId,action,body={}}){switch(action){case'obs_bridge_get':return{bridge:publicBridge(await findOwnedBridge(sql,ownerUserId,body.bridge_id))};case'obs_bridge_create':return createOrRotateBridge(sql,ownerUserId,body.name);case'obs_bridge_revoke':{const b=await findOwnedBridge(sql,ownerUserId,body.bridge_id);if(!b)throw makeError('OBS bridge not found','OBS_BRIDGE_NOT_FOUND',404);const [r]=await sql`UPDATE creapd.obs_bridges SET revoked_at=now(),status='revoked',obs_connected=false,updated_at=now() WHERE id=${b.id} AND owner_user_id=${String(ownerUserId)} RETURNING *`;resetAgentCaches();return{bridge:publicBridge(r),revoked:true};}case'obs_segment_scene_save':return saveTalkSegmentScene(sql,ownerUserId,body);case'obs_command_enqueue':return enqueueCommand(sql,ownerUserId,body);default:throw makeError('Unsupported OBS bridge action','OBS_BRIDGE_ACTION_UNSUPPORTED');}}
const jsonEqual=(a,b)=>JSON.stringify(a??null)===JSON.stringify(b??null);
function heartbeatNeedsWrite(b,n){const last=b?.last_seen_at?new Date(b.last_seen_at).getTime():NaN;if(!Number.isFinite(last)||Date.now()-last>=AGENT_HEARTBEAT_WRITE_MS)return true;if(Boolean(b.obs_connected)!==n.obsConnected)return true;if(n.currentScene&&n.currentScene!==cleanNullable(b.current_scene))return true;if(n.endpoint&&n.endpoint!==cleanNullable(b.obs_endpoint))return true;if(n.studioVersion&&n.studioVersion!==cleanNullable(b.obs_studio_version))return true;if(n.websocketVersion&&n.websocketVersion!==cleanNullable(b.obs_websocket_version))return true;if(n.lastError!==cleanNullable(b.last_error))return true;if(n.scenes.length>0&&!jsonEqual(n.scenes,b.scenes||[]))return true;if(Object.keys(n.capabilities).length>0&&!jsonEqual(n.capabilities,b.capabilities||{}))return true;return false;}
async function updateBridgeHeartbeat(sql,bridge,body){const n={obsConnected:Boolean(body.obs_connected),scenes:normalizeScenes(body.scenes),currentScene:cleanNullable(body.current_scene),endpoint:cleanNullable(body.obs_endpoint),studioVersion:cleanNullable(body.obs_studio_version),websocketVersion:cleanNullable(body.obs_websocket_version),lastError:Boolean(body.obs_connected)?null:cleanNullable(body.last_error),capabilities:body.capabilities&&typeof body.capabilities==='object'&&!Array.isArray(body.capabilities)?body.capabilities:{}};if(!heartbeatNeedsWrite(bridge,n))return false;const status=n.obsConnected?'connected':'bridge_online';await sql`UPDATE creapd.obs_bridges SET status=${status},obs_connected=${n.obsConnected},obs_endpoint=COALESCE(${n.endpoint},obs_endpoint),obs_studio_version=COALESCE(${n.studioVersion},obs_studio_version),obs_websocket_version=COALESCE(${n.websocketVersion},obs_websocket_version),current_scene=COALESCE(${n.currentScene},current_scene),scenes=CASE WHEN ${n.scenes.length}>0 THEN ${JSON.stringify(n.scenes)}::jsonb ELSE scenes END,capabilities=CASE WHEN ${Object.keys(n.capabilities).length}>0 THEN ${JSON.stringify(n.capabilities)}::jsonb ELSE capabilities END,last_seen_at=now(),last_error=${n.lastError},updated_at=now() WHERE id=${bridge.id} AND revoked_at IS NULL`;bridge.status=status;bridge.obs_connected=n.obsConnected;bridge.current_scene=n.currentScene||bridge.current_scene;if(n.scenes.length)bridge.scenes=n.scenes;if(Object.keys(n.capabilities).length)bridge.capabilities=n.capabilities;bridge.last_seen_at=new Date().toISOString();bridge.last_error=n.lastError;return true;}
async function claimPendingCommands(sql,bridgeId){return sql`WITH picked AS (SELECT id FROM creapd.obs_commands WHERE bridge_id=${bridgeId} AND status='pending' ORDER BY requested_at ASC LIMIT 12 FOR UPDATE SKIP LOCKED) UPDATE creapd.obs_commands c SET status='sent',sent_at=now() FROM picked WHERE c.id=picked.id RETURNING c.id,c.command_type,c.payload,c.requested_at`;}
async function completeCommand(sql,bridge,body){const id=clean(body.command_id);if(!id)throw makeError('command_id is required','OBS_COMMAND_ID_REQUIRED');const success=Boolean(body.success),result=body.result&&typeof body.result==='object'?body.result:{};const [command]=await sql`UPDATE creapd.obs_commands SET status=${success?'complete':'failed'},completed_at=now(),result=${json(result)}::jsonb,error_message=${success?null:cleanNullable(body.error)} WHERE id=${id} AND bridge_id=${bridge.id} RETURNING id,status,command_type,result,error_message`;if(!command)throw makeError('OBS command not found','OBS_COMMAND_NOT_FOUND',404);return{command};}
export async function runObsBridgeAgentAction({sql,action,body={}}){const bridge=await requireAgentBridge(sql,body.bridge_token);if(action==='obs_bridge_agent_poll'){await updateBridgeHeartbeat(sql,bridge,body);const runtime=agentRuntime.get(bridge.id)||{},now=Date.now();let commands=[];if(!runtime.lastCommandPollAt||now-runtime.lastCommandPollAt>=AGENT_COMMAND_POLL_MS){commands=await claimPendingCommands(sql,bridge.id);agentRuntime.set(bridge.id,{...runtime,lastCommandPollAt:now});}return{bridge_id:bridge.id,commands,next_poll_ms:AGENT_COMMAND_POLL_MS};}if(action==='obs_bridge_agent_complete')return completeCommand(sql,bridge,body);throw makeError('Unsupported OBS agent action','OBS_AGENT_ACTION_UNSUPPORTED');}
