import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

/**
 * RPP-AI-001 §10 — Review Worker
 * Critiques generated assets before QA evaluation.
 * No Worker may approve its own work (Canonical Rule #9).
 * Capability: reasoning (GPT)
 * Output: Review critique
 */

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { asset_content, asset_type, generating_worker_id, dossier_context, review_focus } = await req.json();

    if (!asset_content) {
      return Response.json({ error: 'asset_content is required' }, { status: 400 });
    }

    const prompt = `You are the Review Worker in the CREAPD AI Studio pipeline (RPP-AI-001 §10).

Your mission: Critique the following generated asset.
You may NOT approve it — that is the QA Worker's job (Canonical Rule #9).

ASSET TYPE: ${asset_type || 'Unknown'}
GENERATED BY: ${generating_worker_id || 'Unknown Worker'}

DOSSIER CONTEXT (for factual verification):
${typeof dossier_context === 'string' ? dossier_context : JSON.stringify(dossier_context || {}, null, 2)}

GENERATED CONTENT:
${typeof asset_content === 'string' ? asset_content : JSON.stringify(asset_content, null, 2)}

${review_focus ? `REVIEW FOCUS: ${review_focus}` : ''}

Provide a critique identifying:
1. strengths: What works well
2. weaknesses: What needs improvement
3. missing_elements: What should be there but isn't
4. factual_issues: Any claims that don't match the dossier
5. suggested_improvements: Specific actionable recommendations

Rules:
- Do NOT rewrite the asset. Only critique it.
- Be specific and actionable.
- Check factual accuracy against the dossier context.
- Flag any content not traceable to the dossier.`;

    const result = await base44.integrations.Core.InvokeLLM({
      prompt,
      model: 'gpt_5_4',
      response_json_schema: {
        type: 'object',
        properties: {
          strengths: { type: 'array', items: { type: 'string' } },
          weaknesses: { type: 'array', items: { type: 'string' } },
          missing_elements: { type: 'array', items: { type: 'string' } },
          factual_issues: { type: 'array', items: { type: 'string' } },
          suggested_improvements: { type: 'array', items: { type: 'string' } },
        },
      },
    });

    return Response.json({
      worker_id: 'review_general',
      department: 'all',
      asset_type,
      generating_worker_id,
      critique: result,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});